# Stage 1: Build
FROM node:20.12.0-alpine AS builder

WORKDIR /app
COPY . .

# Install dependencies and build the project
RUN npm install
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Copy build output to Nginx's public directory
COPY --from=builder /app/build /usr/share/nginx/html

# Expose port 80 and start Nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
