# Use a Node base image for building
FROM node:20.12.0-alpine AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Serve the built app with a lightweight web server
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# Optional: expose port (default NGINX is 80)
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
